name: 🎨 Theme Suggestion
description: Suggest a new theme idea for the community to implement
title: "[Theme Idea]: "
labels: ["theme", "new-theme", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a cool new countdown theme? Share it here!
        
        **Tip**: Enter your theme name in the issue title above (after `[Theme Idea]: `).
        
        ⚠️ **Privacy Note**: Issues are public and visible to everyone. Please check your descriptions and any attached images for personal information before submitting.

  - type: textarea
    id: description
    attributes:
      label: Theme Description
      description: Describe what this theme would look and feel like. Include colors, animations, and the overall vibe.
      placeholder: |
        Example: A neon-lit cyberpunk theme with electric blue and hot pink colors. 
        Numbers glow and pulse. When the countdown ends, a glitch effect takes over 
        with digital artifacts cascading down the screen.
    validations:
      required: true

  - type: dropdown
    id: animation-style
    attributes:
      label: Animation Intensity
      description: How animated should this theme be?
      options:
        - Static (no animations)
        - Subtle (minimal, gentle animations)
        - Animated (moderate animations throughout)
        - Intense (heavy animations, especially near countdown end)
    validations:
      required: true

  - type: textarea
    id: inspiration
    attributes:
      label: Visual Inspiration (Optional)
      description: Links to images, websites, or references that capture the vibe
      placeholder: "Add links to similar visual styles, color palettes, or screenshots"
    validations:
      required: false

  - type: dropdown
    id: implementation-interest
    attributes:
      label: Would you like to implement this theme?
      description: Let us know if you'd like to build this yourself
      options:
        - "I'd like to implement this myself"
        - "I could implement it with some guidance"
        - "I'm just sharing the idea for others to implement"
      default: 2
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/chrisreddington/timestamp/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
